services:
  - type: web
    name: kripto-v1-frankfurt
    runtime: docker
    region: frankfurt
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BINANCE_API_KEY
        sync: false
      - key: BINANCE_ED25519_PRIVATE_KEY
        sync: false
